apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: vpro-ingress
spec:
  ingressClassName: nginx 
  rules:
  - host: vprofile.piustech.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vproapp-svc
            port: 
              number: 8080
